### ISSUE TITLE
EN dates in the minified export not monotonically increasing

### ISSUE THREAD

**Issue by srishanbhattarai** [mesaugat/bikram-sambat-anno-domini-fixtures#1]
If I understand correctly, both EN and NP dates for each array index `i` should be strictly less than array index `i+1` i.e. it should monotonically increase into the future.

I might have a case where this does not hold true. Check indices `9132` and `9132 + 264 = 9394`.
It's cumbersome to deal with the large JSON in the browser so I curl'd the minified export from commit `67989f2`.

```
 curl https://raw.githubusercontent.com/mesaugat/bikram-sambat-anno-domini-fixtures/67989f277816566067a53ac446e558ed94cc489c/export-minified.json > ref_67989f277816566067a53ac446e558ed94cc489c.json
```

I wrote this small JS script:
```js
const fs = require('fs')

const file = fs.readFileSync("ref_67989f277816566067a53ac446e558ed94cc489c.min.json")
const refs = JSON.parse(file)

const base = 9132 
console.log('Index: ', base, '->', refs[base])

const index = 262
console.log('Index: ', base + index, '->', refs[base + index])
```
The `base` and `index` values are computed from the diff-ing I'm doing over at the `nepcal` repository. 

Summarized results from that script are as follows (in `yy-mm-dd` syntax):

| index | en date | np date |
|-------|--------|----------|
| 9132 | 1943 -4-4 | 2000-1-1 
| 9394 | 1943 -1-1 | 2000-9-17

Here, the NP date moves forward in time, but the EN date moves backward. 

Raw stdout output:
```
Index:  9132 -> {
  npYear: 2000,
  npMonth: 1,
  npDay: 1,
  enYear: 1943,
  enMonth: 4,
  enDay: 14
}

Index:  9394 -> {
  npYear: 2000,
  npMonth: 9,
  npDay: 17,
  enYear: 1943,
  enMonth: 1,
  enDay: 1
}
```

**Comment by srishanbhattarai** [comment]
| index | en date | np date |
|-------|--------|----------|
| 9132 | 1943 -4-4 | 2000-1-1 
| 9394 | 1943 -1-1 | 2000-9-17

Reposted for convenience.

Another perhaps useful point is that `nepcal` computes that the value at index `9394` should have been EN date `1944-01-01`.

Cross checking the results with `nepcal.com` this definitely seems like a bad scraping issue since index `9394` which is correctly scraped as `2000-09-17` B.S. maps to  `1944-01-01` A.D on the website.

<img width="400" alt="nepcal scraper issue" src="https://user-images.githubusercontent.com/24712573/79312908-38832f80-7ec5-11ea-88c6-7a27c52f6162.png">

**Comment by mesaugat** [comment]
@srishanbhattarai Thank you for taking the time to add all these details. The PR with the fix is up. https://github.com/mesaugat/bikram-sambat-anno-domini-fixtures/pull/2

Can you check if this fixes your problem? If it does, I'll merge the PR and close the ticket.

**Comment by srishanbhattarai** [comment]
@mesaugat I created a little script to do this and it looks like there are still some issues in case of year wrapping for EN dates. There are a total of 126 cases for EN dates, but all NP dates are fine.

Here is the output of a script I wrote to figure this out:
```
[EN] Prev 262: 1919-12-31, Curr: 263: 1919-01-01
[EN] Prev 627: 1920-12-31, Curr: 628: 1920-01-01
[EN] Prev 993: 1921-12-31, Curr: 994: 1921-01-01
[EN] Prev 1358: 1922-12-31, Curr: 1359: 1922-01-01
<-- truncated -->

126 EN dates and 0 NP dates went back in time
```

In all cases, the issue is with the last day of the year i.e. moving from Dec 31 to Jan 1.

The script is as follows:
```js
const fs = require('fs')

const file = fs.readFileSync("ref_fix.json")
const refs = JSON.parse(file)

function enStr(d) {
  const mo = `${d.enMonth}`.padStart(2, '0')
  const day = `${d.enDay}`.padStart(2, '0')

  return `${d.enYear}-${mo}-${day}`
}

function npStr(d) {
  const mo = `${d.npMonth}`.padStart(2, '0')
  const day = `${d.npDay}`.padStart(2, '0')

  return `${d.npYear}-${mo}-${day}`
}

let en = 0, np = 0

for (let i = 1; i < refs.length; i++) {
  const curr = refs[i]
  const prev = refs[i - 1]

  if (enStr(curr) <= enStr(prev)) {
    console.log(`[EN] Prev ${i-1}: ${enStr(prev)}, Curr: ${i}: ${enStr(curr)}`)
    en++
  }
  
  if (npStr(curr) <= npStr(prev)) {
    console.log(`[NP] Prev ${i-1}: ${npStr(prev)}, Curr: ${i}: ${npStr(curr)}`)
    np++
  }
}

console.log(`\n ${en} EN dates and ${np} NP dates went back in time`)
```

**Comment by mesaugat** [comment]
@srishanbhattarai It might work now.
